# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genquotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genquotes',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
