# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('genquotes', '0003_auto_20170324_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 0, 13, 29, 912656, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
