# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genquotes', '0004_quote_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoicQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('quote_text', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='Quote',
            new_name='CSQuote',
        ),
    ]
