# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genquotes', '0005_auto_20170330_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csquote',
            name='pub_date',
        ),
    ]
