# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genquotes', '0006_remove_csquote_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoicquote',
            name='pub_date',
        ),
    ]
